### ISSUE TITLE
can't register as a new user

### ISSUE THREAD

**Issue by gubsheep** [joeltg/zkmessage.xyz#17]
Just tried to register as a fresh test user ([tweet](https://twitter.com/dftest15/status/1475740088554295298)). The tweet is definitely up but I'm getting this error on attempting to verify:
![telegram-cloud-photo-size-1-5069080919008193040-y](https://user-images.githubusercontent.com/16885693/147544160-27957a6b-c9fb-43d3-94ba-fe21a0e09653.jpg)

**Comment by joeltg** [comment]
this was incredibly confusing until i realized this only happens about 30% of the time (if the public key starts with a zero in hex) 😑

fixed in 6f52ac2bf45937ce10290541748b019791047b46
