### ISSUE TITLE
make it clearer that only group members can post to threads

### ISSUE THREAD

**Issue by gubsheep** [joeltg/zkmessage.xyz#18]

**Comment by joeltg** [comment]
fixed in 64a0fc93c6afb6c0f5a12b1b798c5b89a54770e5

<img width="929" alt="B0EF183C-B72A-4A61-AC69-D87AE4AD404E-8462-0001B933345AA2CA" src="https://user-images.githubusercontent.com/8454646/147693701-56957234-7a6b-4007-ba79-8b0122ee15c6.png">
