### ISSUE TITLE
in signup flow, "next" after copying secret key doesn't do anything

### ISSUE THREAD

**Issue by gubsheep** [joeltg/zkmessage.xyz#21]
On Brave Browser. I've signed in on a different account before so I'm not sure if that's an issue. The screen that I can't get past is pasted below

![image](https://user-images.githubusercontent.com/16885693/148169764-85406bb0-e831-4bce-820c-c0e255ccb2f1.png)

**Comment by joeltg** [comment]
ah the inner link only fit the text not the container, fixed in b6b932c8fad4bd1df794d18a0aa2fdbc444444a2

<img width="829" alt="DD741983-5641-4E07-A37F-66F7E3324BCE-703-0000F509775CD1EE" src="https://user-images.githubusercontent.com/8454646/148244292-f6abcd4a-2ac4-4077-b6be-3f0b4e35300c.png">
